# Copyright © 2026 ReactVision
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

require "json"

# This Podspec wraps the code generated by Codegen for the visionOS Native Modules this package
# adds on top of React Native. It is generated when the package is packed, not when an app installs
# it, so it ships here rather than in the app's ReactCodegen pod.

package = JSON.parse(File.read(File.join(__dir__, "..", "package.json")))
version = package['version']

source = { :git => 'https://github.com/ReactVision/react-native-visionos.git' }
if version == '1000.0.0'
  # This is an unpublished version, use the latest commit hash of the react-native repo, which we’re presumably in.
  source[:commit] = `git rev-parse HEAD`.strip if system("git rev-parse --git-dir > /dev/null 2>&1")
else
  source[:tag] = "v#{version}"
end

header_search_paths = [
  "\"$(PODS_TARGET_SRCROOT)/FBReactNativeSpec_visionOS\"",
  "\"$(PODS_ROOT)/Headers/Private/Yoga\"",
]

new_arch_flags = ENV['RCT_NEW_ARCH_ENABLED'] == '1' ? ' -DRCT_NEW_ARCH_ENABLED=1' : ''

Pod::Spec.new do |s|
  s.name                   = "React-RCTFBReactNativeSpecVisionOS"
  s.version                = version
  s.summary                = "FBReactNativeSpec for the visionOS modules of React Native."
  s.homepage               = "https://callstack.github.io/react-native-visionos-docs/"
  s.license                = package["license"]
  s.author                 = "Callstack"
  s.platforms              = min_supported_versions
  s.source                 = source
  s.source_files           = "FBReactNativeSpec_visionOS/**/*.{c,h,m,mm,cpp}"
  s.compiler_flags         = new_arch_flags
  s.header_dir             = 'FBReactNativeSpec_visionOS'
  s.pod_target_xcconfig    = {
    "USE_HEADERMAP" => "NO",
    "CLANG_CXX_LANGUAGE_STANDARD" => rct_cxx_language_standard(),
    "HEADER_SEARCH_PATHS" => header_search_paths.join(' '),
  }

  resolve_use_frameworks(s, header_mappings_dir: 'FBReactNativeSpec_visionOS', module_name: "React_RCTFBReactNativeSpecVisionOS")

  s.dependency "React-jsi"
  s.dependency "RCTRequired"
  s.dependency "RCTTypeSafety"
  s.dependency "React-Core"
  s.dependency "React-NativeModulesApple"

  add_dependency(s, "ReactCommon", :subspec => "turbomodule/core", :additional_framework_paths => ["react/nativemodule/core"])
  add_dependency(s, "ReactCommon", :subspec => "turbomodule/bridging", :additional_framework_paths => ["react/nativemodule/bridging"])

  depend_on_js_engine(s)
  add_rn_third_party_dependencies(s)
  add_rncore_dependency(s)
end
